name: chatbot
channels:
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - pip
  - asttokens
  - bzip2
  - ca-certificates
  - colorama
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - libffi
  - libsodium
  - matplotlib-inline
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pickleshare
  - platformdirs
  - prompt-toolkit
  - pure_eval
  - pygments
  - python
  - pyzmq
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - vc
  - vs2015_runtime
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zipp
  - zlib
  - pip:
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - alembic
      - altair
      - aniso8601
      - annotated-types
      - anthropic
      - anyio
      - asgiref
      - astrapy
      - attrs
      - backoff
      - bcrypt
      - beautifulsoup4
      - blinker
      - boto3
      - botocore
      - build
      - cachetools
      - certifi
      - cffi
      - charset-normalizer
      - chroma-hnswlib
      - chromadb
      - click
      - cloudpickle
      - cohere
      - coloredlogs
      - contourpy
      - cryptography
      - cycler
      - databricks-sdk
      - dataclasses-json
      - deepdiff
      - defusedxml
      - deprecated
      - deprecation
      - dill
      - dirtyjson
      - distro
      - dnspython
      - docker
      - docstring-parser
      - durationpy
      - embedchain
      - fastapi
      - fastavro
      - filelock
      - flask
      - flatbuffers
      - fonttools
      - frozenlist
      - fsspec
      - gitdb
      - gitpython
      - google-api-core
      - google-auth
      - google-cloud-aiplatform
      - google-cloud-bigquery
      - google-cloud-core
      - google-cloud-resource-manager
      - google-cloud-storage
      - google-crc32c
      - google-pasta
      - google-resumable-media
      - googleapis-common-protos
      - gptcache
      - graphene
      - graphql-core
      - graphql-relay
      - greenlet
      - grpc-google-iam-v1
      - grpcio
      - grpcio-status
      - grpcio-tools
      - h11
      - h2
      - hpack
      - httpcore
      - httptools
      - httpx
      - httpx-sse
      - huggingface-hub
      - humanfriendly
      - hyperframe
      - idna
      - importlib-metadata
      - importlib-resources
      - itsdangerous
      - jinja2
      - jiter
      - jmespath
      - joblib
      - jsonpatch
      - jsonpath-python
      - jsonpointer
      - jsonschema
      - jsonschema-specifications
      - kiwisolver
      - kubernetes
      - langchain
      - langchain-anthropic
      - langchain-chroma
      - langchain-cohere
      - langchain-community
      - langchain-core
      - langchain-experimental
      - langchain-huggingface
      - langchain-openai
      - langchain-text-splitters
      - langchain-unstructured
      - langsmith
      - llama-cloud
      - llama-index
      - llama-index-agent-openai
      - llama-index-cli
      - llama-index-core
      - llama-index-embeddings-openai
      - llama-index-indices-managed-llama-cloud
      - llama-index-legacy
      - llama-index-llms-openai
      - llama-index-multi-modal-llms-openai
      - llama-index-program-openai
      - llama-index-question-gen-openai
      - llama-index-readers-file
      - llama-index-readers-llama-parse
      - llama-parse
      - mako
      - markdown
      - markdown-it-py
      - markupsafe
      - marshmallow
      - matplotlib
      - mdurl
      - mem0ai
      - mlflow
      - mlflow-skinny
      - mmh3
      - mock
      - monotonic
      - mpmath
      - multidict
      - multiprocess
      - mypy-extensions
      - narwhals
      - neo4j
      - networkx
      - nltk
      - numpy
      - oauthlib
      - ollama
      - onnxruntime
      - openai
      - opentelemetry-api
      - opentelemetry-exporter-otlp-proto-common
      - opentelemetry-exporter-otlp-proto-grpc
      - opentelemetry-instrumentation
      - opentelemetry-instrumentation-asgi
      - opentelemetry-instrumentation-fastapi
      - opentelemetry-proto
      - opentelemetry-sdk
      - opentelemetry-semantic-conventions
      - opentelemetry-util-http
      - orderly-set
      - orjson
      - overrides
      - pandas
      - parameterized
      - pathos
      - pdfminer-six
      - pdfplumber
      - pillow
      - portalocker
      - posthog
      - pox
      - ppft
      - propcache
      - proto-plus
      - protobuf
      - psutil
      - pulsar-client
      - pyarrow
      - pyasn1
      - pyasn1-modules
      - pycparser
      - pydantic
      - pydantic-core
      - pydantic-settings
      - pydeck
      - pymongo
      - pymupdf
      - pyparsing
      - pypdf
      - pypdfium2
      - pypika
      - pyproject-hooks
      - pyreadline3
      - pysbd
      - python-dateutil
      - python-dotenv
      - pytz
      - pywin32
      - pyyaml
      - qdrant-client
      - rank-bm25
      - referencing
      - regex
      - requests
      - requests-oauthlib
      - requests-toolbelt
      - rich
      - rpds-py
      - rsa
      - s3transfer
      - safetensors
      - schema
      - scikit-learn
      - scipy
      - sentence-transformers
      - shapely
      - shellingham
      - smdebug-rulesconfig
      - smmap
      - sniffio
      - soupsieve
      - sqlalchemy
      - sqlparse
      - st-chat-message
      - starlette
      - streamlit
      - streamlit-chat
      - striprtf
      - sympy
      - tabulate
      - tblib
      - tenacity
      - threadpoolctl
      - tiktoken
      - tokenizers
      - toml
      - torch
      - tqdm
      - transformers
      - typer
      - types-requests
      - typing-inspect
      - tzdata
      - unstructured-client
      - urllib3
      - uuid6
      - uvicorn
      - waitress
      - watchdog
      - watchfiles
      - websocket-client
      - websockets
      - werkzeug
      - wrapt
      - yarl