cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    roylwz:
      email: elroy7602@gmail.com
      first_name: Elroy
      last_name: Lian
      logged_in: false
      password: $2b$12$dknIOTMKMeYsGWzvZu5fkObNdmaoxR6dvIEuYDPn7dEW8AlA4hu7K
      password_hint: abcde123!
      roles: null
