cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    roylwz:
      email: elroy7602@gmail.com
      first_name: Elroy
      last_name: Lian
      logged_in: false
      password: $2b$12$dknIOTMKMeYsGWzvZu5fkObNdmaoxR6dvIEuYDPn7dEW8AlA4hu7K
      password_hint: abcde123!
      roles:
      - user
    testuser:
      email: testuser@gmail.com
      first_name: Test
      last_name: User
      logged_in: false
      password: $2b$12$dI17BU1VBL.i6Hu9mMQSnux9ShVnXoTF/u3KH4OjgsPK3gc59FBRy
      password_hint: Abcde123!
      roles:
      - user
      - tester
