cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    roylwz:
      email: elroy7602@gmail.com
      first_name: Elroy
      last_name: Lian
      logged_in: false
      password: $2b$12$CrncArl1neReuBJrYhsCaehRQ4mtwlBXJJA1J/0MfvQJWv/PMfxRG
      password_hint: Abcde123!
      roles:
      - user
      - tester
    roylwz2:
      email: elroy2304@gmail.com
      first_name: Elroy
      last_name: Test
      logged_in: false
      password: $2b$12$BkKHz.z2a2LKPEV5spChZ.ffkcZ2nyDVU6KvdOSsbqk/NK3IqNMEW
      password_hint: Abcde123!
      roles:
      - user
